package com.comp2042;

/**
 * Enumeration representing the source of a game event.
 * Distinguishes between user-initiated events and system/thread-generated events.
 */
public enum EventSource {
    /** Event initiated by user input (keyboard). */
    USER,
    /** Event generated by the game thread (automatic movement). */
    THREAD
}
